// Ícones selecionados para categorias e ambientes (todos incluídos na fonte embutida).
export const ICONES_CATEGORIA: { grupo: string; icones: string[] }[] = [
  { grupo: 'Casa e contas', icones: ['home', 'apartment', 'cottage', 'receipt', 'bolt', 'water_drop', 'wifi', 'propane_tank', 'cleaning_services', 'local_laundry_service', 'chair', 'bed', 'build', 'handyman', 'plumbing', 'yard', 'kitchen', 'light', 'roofing', 'key', 'garage', 'shower', 'ac_unit', 'tv', 'local_florist', 'deck', 'solar_power', 'gas_meter', 'electric_meter', 'water', 'fire_extinguisher', 'lock'] },
  { grupo: 'Comida e compras', icones: ['shopping_cart', 'local_grocery_store', 'shopping_basket', 'restaurant', 'fastfood', 'local_pizza', 'bakery_dining', 'local_cafe', 'icecream', 'local_bar', 'liquor', 'shopping_bag', 'local_mall', 'storefront', 'checkroom', 'dry_cleaning', 'lunch_dining', 'ramen_dining', 'set_meal', 'egg', 'kebab_dining', 'local_drink', 'wine_bar', 'sports_bar', 'coffee', 'nutrition', 'cookie', 'delivery_dining', 'takeout_dining', 'soup_kitchen'] },
  { grupo: 'Transporte', icones: ['directions_car', 'local_gas_station', 'ev_station', 'toll', 'local_parking', 'car_repair', 'tire_repair', 'two_wheeler', 'local_taxi', 'directions_bus', 'train', 'flight', 'directions_bike', 'electric_scooter', 'electric_car', 'directions_boat', 'subway', 'tram', 'commute', 'minor_crash', 'car_rental', 'airport_shuttle', 'local_car_wash', 'traffic', 'map'] },
  { grupo: 'Saúde e cuidados', icones: ['medical_services', 'local_pharmacy', 'medication', 'local_hospital', 'dentistry', 'vaccines', 'psychology', 'spa', 'fitness_center', 'brush', 'content_cut', 'face', 'monitor_heart', 'favorite', 'healing', 'emergency', 'medical_information', 'hearing', 'visibility', 'eyeglasses', 'self_improvement', 'sports_gymnastics', 'directions_run', 'pool', 'sanitizer', 'masks', 'bloodtype'] },
  { grupo: 'Lazer e família', icones: ['sports_esports', 'sports_soccer', 'theaters', 'movie', 'music_note', 'beach_access', 'hotel', 'luggage', 'park', 'celebration', 'cake', 'card_giftcard', 'redeem', 'pets', 'child_care', 'family_restroom', 'elderly', 'church', 'volunteer_activism', 'diamond', 'sports_basketball', 'sports_tennis', 'sports_volleyball', 'golf_course', 'surfing', 'hiking', 'camping', 'attractions', 'casino', 'nightlife', 'stadium', 'palette', 'photo_camera', 'headphones', 'auto_stories', 'toys', 'stroller', 'crib', 'cruelty_free', 'mood'] },
  { grupo: 'Estudo e trabalho', icones: ['school', 'menu_book', 'book', 'local_library', 'work', 'business_center', 'engineering', 'badge', 'groups', 'computer', 'smartphone', 'devices', 'cloud', 'subscriptions', 'campaign', 'inventory_2', 'local_shipping', 'calculate', 'description', 'gavel', 'security', 'print', 'construction', 'architecture', 'science', 'biotech', 'draw', 'design_services', 'agriculture', 'factory', 'warehouse', 'precision_manufacturing', 'support_agent', 'mail', 'call', 'router', 'memory', 'language', 'public'] },
  { grupo: 'Dinheiro', icones: ['payments', 'account_balance_wallet', 'account_balance', 'savings', 'paid', 'attach_money', 'request_quote', 'credit_card', 'wallet', 'percent', 'trending_up', 'sell', 'handshake', 'move_to_inbox', 'label', 'more_horiz', 'currency_exchange', 'price_check', 'receipt_long', 'point_of_sale', 'qr_code', 'monitoring', 'insights', 'pie_chart', 'show_chart', 'trending_down', 'money_off', 'local_atm', 'euro', 'currency_bitcoin'] },
  { grupo: 'Símbolos', icones: ['star', 'bookmark', 'flag', 'push_pin', 'schedule', 'event', 'calendar_month', 'alarm', 'notifications', 'lightbulb', 'eco', 'recycling', 'home_work', 'sunny', 'dark_mode', 'rocket_launch', 'emoji_events', 'military_tech', 'verified', 'warning', 'info', 'help'] },
  // Letras e números: "txt:X" é desenhado como texto, não como ícone da fonte
  { grupo: 'Letras e números', icones: ['txt:A', 'txt:B', 'txt:C', 'txt:D', 'txt:E', 'txt:F', 'txt:G', 'txt:H', 'txt:I', 'txt:J', 'txt:K', 'txt:L', 'txt:M', 'txt:N', 'txt:O', 'txt:P', 'txt:Q', 'txt:R', 'txt:S', 'txt:T', 'txt:U', 'txt:V', 'txt:W', 'txt:X', 'txt:Y', 'txt:Z', 'txt:0', 'txt:1', 'txt:2', 'txt:3', 'txt:4', 'txt:5', 'txt:6', 'txt:7', 'txt:8', 'txt:9'] },
]

export const ICONES_AMBIENTE = ['person', 'business_center', 'home', 'store', 'storefront', 'family_restroom', 'savings', 'folder', 'work', 'apartment', 'directions_car', 'school']
